Add new code owner
nextcloud/twofactor_admin pull request #285
Opened 2023-05-09 16:16 UTC by vitormattos

2023-05-09 17:43 UTC, ChristophWurst requested changes
I'm just the backup :)

2023-05-10 08:48 UTC, ChristophWurst approved these changes
Squash and merge

2023-05-10 08:50 UTC, vitormattos commented on .github/CODEOWNERS
> +*	@ChristophWurst @vitormattos
Done, but only to know more: What this order affect? Looking at this documentation I didn't found info about the order:
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners

2023-05-10 08:57 UTC, ChristophWurst commented on .github/CODEOWNERS
> +*	@ChristophWurst @vitormattos
I don't think it matters for Github

2023-06-22 15:50 UTC, closed without merging